const products = [
    {
      id: 0,
      name: "Iphone 11",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "iphone",
      price: 700,
      image: "./images/iphone-11.jpg",
      sale: true,
      saleAmount: 200,
    },
    {
      id: 1,
      name: "Iphone 13",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "iphone",
      price: 900,
      image: "./images/iphone-13.jpg",
    },
    {
      id: 2,
      name: "Iphone 12",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "iphone",
      price: 800,
      image: "./images/Iphone-12.jpg",
      sale: true,
      saleAmount: 151,
    },
    {
      id: 3,
      name: "huawei p50 pro",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "huawei",
      price: 250,
      image: "./images/huawei-2.jpg",
    },
    {
      id: 4,
      name: "huawei p20 lite",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "huawei",
      price: 400,
      image: "./images/huawei-1.jpg",
    },
    {
      id: 5,
      name: "Nokia c300",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "nokia",
      price: 180,
      image: "./images/Nokia.jpg",
      sale: true,
      saleAmount: 50,
    },
    {
      id: 6,
      name: "Nokia n70",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "nokia",
      price: 140,
      image: "./images/Nokia-2.jpg",
    },
    {
      id: 7,
      name: "Samsung a53",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "samsung",
      price: 320,
      image: "./images/Samsung-a53.jpg",
    },
    {
      id: 8,
      name: "Samsung s20",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "samsung",
      price: 500,
      image: "./images/Samsung-s20.jpg",
      sale: true,
      saleAmount: 50,
    },
    {
      id: 9,
      name: "Samsung s22",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "samsung",
      price: 700,
      image: "./images/Samsung-s22.jpg",
    },
  ];
